services:
  kafka:
<<<<<<< HEAD
    image: confluentinc/cp-kafka:7.6.0
=======
    image: confluentinc/cp-kafka:7.5.0
>>>>>>> f33ed383d8e88d290a27dd7885af588db7e1ce40
    container_name: sentinela-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
<<<<<<< HEAD
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  simulator:
    build: ./services/simulator
    container_name: sentinela-simulator
    depends_on:
      - kafka
=======
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
>>>>>>> f33ed383d8e88d290a27dd7885af588db7e1ce40
    restart: unless-stopped

  rule-engine:
    build: ./services/rule_engine
<<<<<<< HEAD
    container_name: sentinela-rule-engine
    depends_on:
      - kafka
    restart: unless-stopped
=======
    container_name: sentinela-rule-engine-1
    depends_on:
      - kafka

  alert-sink:
    build: ./services/alert-sink
    container_name: sentinela-alert-sink-1
    depends_on:
      - kafka

  simulator:
    build: ./services/simulator
    container_name: sentinela-simulator-1
    depends_on:
      - kafka

  db:
    image: postgres:15
    container_name: sentinela-db
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  dashboard-api:
    build: ./services/dashboard_api
    container_name: sentinela-dashboard-api
    ports:
      - "5000:5000"
    depends_on:
      - db

  dashboard-web:
    build: ./services/dashboard_web
    container_name: sentinela-dashboard-web
    ports:
      - "80:80"
    depends_on:
      - dashboard-api
>>>>>>> f33ed383d8e88d290a27dd7885af588db7e1ce40
