[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    storage.path /var/fluent-bit/state
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 16M

[INPUT]
    Name              tail
    Tag               sentinela.logs.raw
    Path              /host/var/log/auth.log
    Parser            syslog
    DB                /var/fluent-bit/state/auth.db
    Mem_Buf_Limit     8MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    storage.type      filesystem

[INPUT]
    Name              tail
    Tag               sentinela.logs.raw
    Path              /host/var/log/syslog,/host/var/log/messages
    Parser            syslog
    DB                /var/fluent-bit/state/syslog.db
    Mem_Buf_Limit     8MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    storage.type      filesystem

[INPUT]
    Name              tail
    Tag               sentinela.logs.raw
    Path              /host/var/log/nginx/access.log,/host/var/log/nginx/error.log
    Parser            nginx
    DB                /var/fluent-bit/state/nginx.db
    Mem_Buf_Limit     8MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    storage.type      filesystem

[INPUT]
    Name              tail
    Tag               sentinela.logs.raw
    Path              /host/var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /var/fluent-bit/state/docker.db
    Mem_Buf_Limit     12MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    storage.type      filesystem

[INPUT]
    Name              systemd
    Tag               sentinela.logs.raw
    Systemd_Filter    _SYSTEMD_UNIT=ssh.service
    Systemd_Filter    _SYSTEMD_UNIT=sshd.service
    Systemd_Filter    _SYSTEMD_UNIT=sudo.service
    DB                /var/fluent-bit/state/systemd.db
    Read_From_Tail    On
    Strip_Underscores On

[FILTER]
    Name         modify
    Match        *
    Add          sentinela_source fluent-bit
    Add          event_schema_version sentinela.raw.v1

[OUTPUT]
    Name          nats
    Match         sentinela.logs.raw
    Host          ${NATS_HOST}
    Port          ${NATS_PORT}
