protected_ips:
  - "127.0.0.1"
  - "::1"

protected_cidrs:
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"

protected_hosts:
  - "localhost"
  - "sentinela-db"
  - "sentinela-kafka"
  - "sentinela-redis"
  - "sentinela-rule-engine"

protected_containers:
  - "sentinela-db"
  - "sentinela-kafka"
  - "sentinela-redis"
  - "sentinela-rule-engine"

protected_tenants:
  - "admin"
