apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinela

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.example.yaml
  - networkpolicy.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - jaeger.yaml
  - dashboard-api.yaml
  - dashboard-web.yaml
  - pipeline-workers.yaml
  - observability.yaml
  - ingress.yaml

images:
  - name: sentinela/dashboard-api
    newName: ghcr.io/leivybispo/sentinela-dashboard-api
    newTag: latest
  - name: sentinela/dashboard-web
    newName: ghcr.io/leivybispo/sentinela-dashboard-web
    newTag: latest
  - name: sentinela/log-collector
    newName: ghcr.io/leivybispo/sentinela-log-collector
    newTag: latest
  - name: sentinela/enrichment-worker
    newName: ghcr.io/leivybispo/sentinela-enrichment-worker
    newTag: latest
  - name: sentinela/rule-engine
    newName: ghcr.io/leivybispo/sentinela-rule-engine
    newTag: latest
  - name: sentinela/alert-sink
    newName: ghcr.io/leivybispo/sentinela-alert-sink
    newTag: latest
