apiVersion: v1
kind: Namespace
metadata:
  name: sentinela
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinela-config
  namespace: sentinela
data:
  KAFKA_BOOTSTRAP_SERVERS: "sentinela-kafka:9092"
  DB_HOST: "sentinela-db"
  DB_NAME: "postgres"
  RETENTION_ALERTS_DAYS: "30"
  AUTO_RESPONSE_MODE: "simulated"
