global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: sentinela-dashboard-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - dashboard_api:5000
    authorization:
      type: Bearer
      credentials: sentinela-demo-token

  - job_name: sentinela-log-collector
    metrics_path: /metrics
    static_configs:
      - targets:
          - log_collector:8000

  - job_name: sentinela-rule-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - rule_engine:8001

  - job_name: sentinela-enrichment-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - enrichment-worker:8000

  - job_name: sentinela-alert-sink
    metrics_path: /metrics
    static_configs:
      - targets:
          - alert_sink:8000

  - job_name: sentinela-simulator
    metrics_path: /metrics
    static_configs:
      - targets:
          - simulator:8000

  - job_name: sentinela-dashboard-web
    metrics_path: /metrics
    static_configs:
      - targets:
          - dashboard_web_exporter:9113

  - job_name: sentinela-kafka-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka_exporter:9308

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
