apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml

patches:
  - path: patch-prod.yaml
  - path: patch-multinode.yaml

images:
  - name: ghcr.io/leivybispo/sentinela-dashboard-api
    newTag: stable
  - name: ghcr.io/leivybispo/sentinela-dashboard-web
    newTag: stable
  - name: ghcr.io/leivybispo/sentinela-log-collector
    newTag: stable
  - name: ghcr.io/leivybispo/sentinela-enrichment-worker
    newTag: stable
  - name: ghcr.io/leivybispo/sentinela-rule-engine
    newTag: stable
  - name: ghcr.io/leivybispo/sentinela-alert-sink
    newTag: stable
